/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interface;
import Business.Car;
import javax.swing.JOptionPane;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.IOException;
import javax.imageio.ImageIO;
import javax.swing.JFileChooser;
/**
 *
 * @author wangbochao
 */
public class CreatePanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPanel
     */
    private Car car;
    
    public CreatePanel(Car car) {
        initComponents();
        this.car=car;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane = new javax.swing.JTabbedPane();
        BasicPanel = new javax.swing.JPanel();
        createBasicBtn = new javax.swing.JButton();
        carNameLabel = new javax.swing.JLabel();
        carNameTextField = new javax.swing.JTextField();
        modelLabel = new javax.swing.JLabel();
        modelComboBox = new javax.swing.JComboBox<>();
        priceLabel = new javax.swing.JLabel();
        priceTextField = new javax.swing.JTextField();
        dollarLabel = new javax.swing.JLabel();
        exteriorColorTextField = new javax.swing.JTextField();
        exteriorColorLabel = new javax.swing.JLabel();
        productionYearLabel = new javax.swing.JLabel();
        productionYearTextField = new javax.swing.JTextField();
        serialNumberLabel = new javax.swing.JLabel();
        serialNumberTextField = new javax.swing.JTextField();
        fuelTypeLabel = new javax.swing.JLabel();
        fuelTypeComboBox = new javax.swing.JComboBox<>();
        uploadBtn = new javax.swing.JButton();
        imageLabel = new javax.swing.JLabel();
        createCarLabel = new javax.swing.JLabel();
        advancedPanel = new javax.swing.JPanel();
        saveAdvanceBtn = new javax.swing.JButton();
        dimensionsLabel = new javax.swing.JLabel();
        lengthLabel = new javax.swing.JLabel();
        lengthTextField = new javax.swing.JTextField();
        widthLabel = new javax.swing.JLabel();
        widthTextField = new javax.swing.JTextField();
        heightLabel = new javax.swing.JLabel();
        heightTextField = new javax.swing.JTextField();
        seatQuantityLabel = new javax.swing.JLabel();
        seatQuantityTextField = new javax.swing.JTextField();
        seatTypeLabel = new javax.swing.JLabel();
        seatTypeComboBox = new javax.swing.JComboBox<>();
        fuelCapacityLabel = new javax.swing.JLabel();
        fuelCapacityTextField = new javax.swing.JTextField();
        gallonLabel1 = new javax.swing.JLabel();
        maxCargoCapacityLabel = new javax.swing.JLabel();
        maxCargoCapacityTextField = new javax.swing.JTextField();
        fuelConsumptionLabel = new javax.swing.JLabel();
        fuelConsumptionTextField = new javax.swing.JTextField();
        gallonLabel2 = new javax.swing.JLabel();
        engineLabel = new javax.swing.JLabel();
        engineTextField = new javax.swing.JTextField();
        transmissionLabel = new javax.swing.JLabel();
        transmissionComboBox = new javax.swing.JComboBox<>();
        drivetrainLabel = new javax.swing.JLabel();
        drivetrainComboBox = new javax.swing.JComboBox<>();
        navigationSystemLabel = new javax.swing.JLabel();
        navigationSystemComboBox = new javax.swing.JComboBox<>();
        keylessStartLabel = new javax.swing.JLabel();
        keylessStartComboBox = new javax.swing.JComboBox<>();
        mpgLabel = new javax.swing.JLabel();

        createBasicBtn.setText("Create");
        createBasicBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createBasicBtnActionPerformed(evt);
            }
        });

        carNameLabel.setText("Car Name");

        modelLabel.setText("Model");

        modelComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Small", "Mini","Compact","medium","advanced","luxury","Sedan","SUV","MDV","CDV"}));
        modelComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelComboBoxActionPerformed(evt);
            }
        });

        priceLabel.setText("Price");

        priceTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFieldActionPerformed(evt);
            }
        });

        dollarLabel.setText("$");

        exteriorColorLabel.setText("Exterior Color");

        productionYearLabel.setText("Production Year");

        productionYearTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                productionYearTextFieldActionPerformed(evt);
            }
        });

        serialNumberLabel.setText("Serial Number");

        serialNumberTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                serialNumberTextFieldActionPerformed(evt);
            }
        });

        fuelTypeLabel.setText("Fuel Type");

        fuelTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "electric ","gas"}));
        fuelTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelTypeComboBoxActionPerformed(evt);
            }
        });

        uploadBtn.setText("Upload Picture");
        uploadBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                uploadBtnActionPerformed(evt);
            }
        });

        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/defaultimage/defaultCar.png"))); // NOI18N

        createCarLabel.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N
        createCarLabel.setText("Create Your Car");

        javax.swing.GroupLayout BasicPanelLayout = new javax.swing.GroupLayout(BasicPanel);
        BasicPanel.setLayout(BasicPanelLayout);
        BasicPanelLayout.setHorizontalGroup(
            BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicPanelLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasicPanelLayout.createSequentialGroup()
                        .addComponent(createCarLabel)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(BasicPanelLayout.createSequentialGroup()
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(BasicPanelLayout.createSequentialGroup()
                                .addGap(106, 106, 106)
                                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(serialNumberLabel, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(fuelTypeLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(serialNumberTextField)
                                    .addComponent(fuelTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicPanelLayout.createSequentialGroup()
                                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(BasicPanelLayout.createSequentialGroup()
                                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(exteriorColorLabel)
                                            .addComponent(productionYearLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED))
                                    .addGroup(BasicPanelLayout.createSequentialGroup()
                                        .addComponent(priceLabel)
                                        .addGap(18, 18, 18))
                                    .addGroup(BasicPanelLayout.createSequentialGroup()
                                        .addComponent(modelLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                                    .addGroup(BasicPanelLayout.createSequentialGroup()
                                        .addComponent(carNameLabel)
                                        .addGap(10, 10, 10)))
                                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(modelComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(exteriorColorTextField)
                                    .addComponent(productionYearTextField)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BasicPanelLayout.createSequentialGroup()
                                        .addGap(6, 6, 6)
                                        .addComponent(dollarLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addComponent(carNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 40, Short.MAX_VALUE)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(BasicPanelLayout.createSequentialGroup()
                                .addComponent(createBasicBtn)
                                .addGap(35, 35, 35)
                                .addComponent(uploadBtn))
                            .addComponent(imageLabel))
                        .addGap(30, 30, 30))))
        );
        BasicPanelLayout.setVerticalGroup(
            BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BasicPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(createCarLabel)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BasicPanelLayout.createSequentialGroup()
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(carNameLabel)
                            .addComponent(carNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(modelLabel)
                            .addComponent(modelComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(priceLabel)
                            .addComponent(priceTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dollarLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(exteriorColorLabel)
                            .addComponent(exteriorColorTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(productionYearLabel)
                            .addComponent(productionYearTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(serialNumberTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(serialNumberLabel)))
                    .addComponent(imageLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(createBasicBtn)
                    .addComponent(uploadBtn)
                    .addGroup(BasicPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(fuelTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(fuelTypeLabel)))
                .addContainerGap())
        );

        jTabbedPane.addTab("Basic", BasicPanel);

        saveAdvanceBtn.setText("Create");
        saveAdvanceBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveAdvanceBtnActionPerformed(evt);
            }
        });

        dimensionsLabel.setText("dimensions (cm)");

        lengthLabel.setText("Length");

        lengthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lengthTextFieldActionPerformed(evt);
            }
        });

        widthLabel.setText("Width");

        widthTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                widthTextFieldActionPerformed(evt);
            }
        });

        heightLabel.setText("Height");

        heightTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                heightTextFieldActionPerformed(evt);
            }
        });

        seatQuantityLabel.setText("Seat Quantity");

        seatQuantityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatQuantityTextFieldActionPerformed(evt);
            }
        });

        seatTypeLabel.setText("Seat Type");

        seatTypeComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Flannel", "Leather","Racing"}));
        seatTypeComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seatTypeComboBoxActionPerformed(evt);
            }
        });

        fuelCapacityLabel.setText("Fuel Capacity");

        fuelCapacityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelCapacityTextFieldActionPerformed(evt);
            }
        });

        gallonLabel1.setText("gallon");

        maxCargoCapacityLabel.setText("Max Cargo Capacity");

        maxCargoCapacityTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxCargoCapacityTextFieldActionPerformed(evt);
            }
        });

        fuelConsumptionLabel.setText("Fuel Consumption");

        fuelConsumptionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fuelConsumptionTextFieldActionPerformed(evt);
            }
        });

        gallonLabel2.setText("gallon");

        engineLabel.setText("Engine");

        engineTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                engineTextFieldActionPerformed(evt);
            }
        });

        transmissionLabel.setText("Transmission Type");

        transmissionComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Manual", "Auto"}));
        transmissionComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                transmissionComboBoxActionPerformed(evt);
            }
        });

        drivetrainLabel.setText("Drivetrain");

        drivetrainComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Front Front", "Front Rear","Rear Front","Rear Rear"}));
        drivetrainComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drivetrainComboBoxActionPerformed(evt);
            }
        });

        navigationSystemLabel.setText("Navigation System");

        navigationSystemComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "None"}));
        navigationSystemComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                navigationSystemComboBoxActionPerformed(evt);
            }
        });

        keylessStartLabel.setText("Keyless Start");

        keylessStartComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Yes", "None"}));
        keylessStartComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                keylessStartComboBoxActionPerformed(evt);
            }
        });

        mpgLabel.setText("mpg");

        javax.swing.GroupLayout advancedPanelLayout = new javax.swing.GroupLayout(advancedPanel);
        advancedPanel.setLayout(advancedPanelLayout);
        advancedPanelLayout.setHorizontalGroup(
            advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedPanelLayout.createSequentialGroup()
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(advancedPanelLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(dimensionsLabel)
                            .addGroup(advancedPanelLayout.createSequentialGroup()
                                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advancedPanelLayout.createSequentialGroup()
                                        .addComponent(lengthLabel)
                                        .addGap(4, 4, 4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, advancedPanelLayout.createSequentialGroup()
                                        .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(heightLabel)
                                            .addComponent(widthLabel)
                                            .addComponent(seatQuantityLabel)
                                            .addComponent(seatTypeLabel)
                                            .addComponent(fuelCapacityLabel))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)))
                                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(heightTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(widthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lengthTextField, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(seatQuantityTextField)
                                    .addComponent(seatTypeComboBox, 0, 85, Short.MAX_VALUE)
                                    .addComponent(fuelCapacityTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(gallonLabel1)))
                        .addGap(75, 75, 75)
                        .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(advancedPanelLayout.createSequentialGroup()
                                    .addGap(26, 26, 26)
                                    .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(engineLabel)
                                        .addComponent(fuelConsumptionLabel)
                                        .addComponent(transmissionLabel)
                                        .addComponent(drivetrainLabel)
                                        .addComponent(navigationSystemLabel)))
                                .addComponent(maxCargoCapacityLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(keylessStartLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(fuelConsumptionTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(engineTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE)
                            .addComponent(transmissionComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(drivetrainComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(navigationSystemComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(keylessStartComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(maxCargoCapacityTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 87, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(gallonLabel2)
                            .addComponent(mpgLabel)))
                    .addGroup(advancedPanelLayout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(saveAdvanceBtn)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        advancedPanelLayout.setVerticalGroup(
            advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(advancedPanelLayout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dimensionsLabel)
                    .addComponent(maxCargoCapacityLabel)
                    .addComponent(maxCargoCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gallonLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lengthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lengthLabel)
                    .addComponent(fuelConsumptionLabel)
                    .addComponent(fuelConsumptionTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(mpgLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(widthLabel)
                    .addComponent(widthTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(engineLabel)
                    .addComponent(engineTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(heightLabel)
                    .addComponent(heightTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(transmissionLabel)
                    .addComponent(transmissionComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatQuantityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(seatQuantityLabel)
                    .addComponent(drivetrainLabel)
                    .addComponent(drivetrainComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(seatTypeLabel)
                    .addComponent(seatTypeComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(navigationSystemLabel)
                    .addComponent(navigationSystemComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(advancedPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(fuelCapacityLabel)
                    .addComponent(fuelCapacityTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(keylessStartLabel)
                    .addComponent(keylessStartComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gallonLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(saveAdvanceBtn)
                .addContainerGap(38, Short.MAX_VALUE))
        );

        jTabbedPane.addTab("Advance", advancedPanel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane, javax.swing.GroupLayout.Alignment.TRAILING)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void saveAdvanceBtnActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // Binding the user input to the advance data object
        car.setLength(lengthTextField.getText());
        car.setWidth(widthTextField.getText());
        car.setHeight(heightTextField.getText());
        car.setSeatQuantity(seatQuantityTextField.getText());
        car.setSeatType((String)seatTypeComboBox.getSelectedItem());
        car.setFuelCapacity(fuelCapacityTextField.getText());
        car.setMaxCargoCapacity(maxCargoCapacityTextField.getText());
        car.setFuelConsumption(fuelConsumptionTextField.getText());
        car.setEngine(engineTextField.getText());
        car.setTransmission((String)transmissionComboBox.getSelectedItem());
        car.setDrivetrain((String)drivetrainComboBox.getSelectedItem());
        car.setNavigationSystem((String)navigationSystemComboBox.getSelectedItem());
        car.setSeatType((String)seatTypeComboBox.getSelectedItem());
        car.setKeylessStart((String)keylessStartComboBox.getSelectedItem());
        
        Image carImg=car.getCarImage();
        if (carImg!=null){
        imageLabel.setIcon(new javax.swing.ImageIcon(carImg));}
        // Prompt user that advance data was successfully created.
        JOptionPane.showMessageDialog(null,"Create Adcance Information Successfully!");
    }

    private void serialNumberTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_serialNumberTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_serialNumberTextFieldActionPerformed

    private void uploadBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_uploadBtnActionPerformed
        // Open File Chooser
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(null);
        switch (result) {
            case JFileChooser.APPROVE_OPTION:
            File imgFile = chooser.getSelectedFile();
            String imgPath = imgFile.getAbsolutePath();
            //Read the image as bufferedimage
            BufferedImage img = null;
            try {
                img = ImageIO.read(new File(imgPath));
            } catch (IOException e) {
                e.printStackTrace();
            }
            //Resize the BufferedImage
            Image dimg = img.getScaledInstance(imageLabel.getWidth(), imageLabel.getHeight(),
                Image.SCALE_SMOOTH);
            //Display Car picture in smooth size
            imageLabel.setIcon(new javax.swing.ImageIcon(dimg));
            car.setCarImage(dimg);
            break;
            case JFileChooser.CANCEL_OPTION:
            break;
            case JFileChooser.ERROR_OPTION:
            break;
            
        }
        JOptionPane.showMessageDialog(null,"Upload Car Image Successfully!");
    }//GEN-LAST:event_uploadBtnActionPerformed

    private void createBasicBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createBasicBtnActionPerformed
        // Binding the user input to the basic object
        car.setCarName(carNameTextField.getText());
        car.setModel((String)modelComboBox.getSelectedItem());
        car.setPrice(priceTextField.getText());
        car.setExteriorColor(exteriorColorTextField.getText());
        car.setProductionYear(productionYearTextField.getText());
        car.setSerialNumber(serialNumberTextField.getText());
        car.setFuelType((String)fuelTypeComboBox.getSelectedItem());
        
        Image carImg=car.getCarImage();
        if (carImg!=null){
        imageLabel.setIcon(new javax.swing.ImageIcon(carImg));}

        // Prompt user that basic was successfully created.
        JOptionPane.showMessageDialog(null,"Create Basic Information Successfully!");
    }//GEN-LAST:event_createBasicBtnActionPerformed

    private void productionYearTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_productionYearTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_productionYearTextFieldActionPerformed

    private void priceTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_priceTextFieldActionPerformed

    private void modelComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_modelComboBoxActionPerformed

    private void lengthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lengthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lengthTextFieldActionPerformed

    private void seatTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatTypeComboBoxActionPerformed

    private void seatQuantityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seatQuantityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_seatQuantityTextFieldActionPerformed

    private void fuelConsumptionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelConsumptionTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelConsumptionTextFieldActionPerformed

    private void fuelCapacityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelCapacityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelCapacityTextFieldActionPerformed

    private void widthTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_widthTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_widthTextFieldActionPerformed

    private void heightTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_heightTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_heightTextFieldActionPerformed

    private void engineTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_engineTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_engineTextFieldActionPerformed

    private void transmissionComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_transmissionComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_transmissionComboBoxActionPerformed

    private void drivetrainComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drivetrainComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_drivetrainComboBoxActionPerformed

    private void navigationSystemComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_navigationSystemComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_navigationSystemComboBoxActionPerformed

    private void keylessStartComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_keylessStartComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_keylessStartComboBoxActionPerformed

    private void maxCargoCapacityTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxCargoCapacityTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxCargoCapacityTextFieldActionPerformed

    private void fuelTypeComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fuelTypeComboBoxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_fuelTypeComboBoxActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BasicPanel;
    private javax.swing.JPanel advancedPanel;
    private javax.swing.JLabel carNameLabel;
    private javax.swing.JTextField carNameTextField;
    private javax.swing.JButton createBasicBtn;
    private javax.swing.JLabel createCarLabel;
    private javax.swing.JLabel dimensionsLabel;
    private javax.swing.JLabel dollarLabel;
    private javax.swing.JComboBox<String> drivetrainComboBox;
    private javax.swing.JLabel drivetrainLabel;
    private javax.swing.JLabel engineLabel;
    private javax.swing.JTextField engineTextField;
    private javax.swing.JLabel exteriorColorLabel;
    private javax.swing.JTextField exteriorColorTextField;
    private javax.swing.JLabel fuelCapacityLabel;
    private javax.swing.JTextField fuelCapacityTextField;
    private javax.swing.JLabel fuelConsumptionLabel;
    private javax.swing.JTextField fuelConsumptionTextField;
    private javax.swing.JComboBox<String> fuelTypeComboBox;
    private javax.swing.JLabel fuelTypeLabel;
    private javax.swing.JLabel gallonLabel1;
    private javax.swing.JLabel gallonLabel2;
    private javax.swing.JLabel heightLabel;
    private javax.swing.JTextField heightTextField;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JTabbedPane jTabbedPane;
    private javax.swing.JComboBox<String> keylessStartComboBox;
    private javax.swing.JLabel keylessStartLabel;
    private javax.swing.JLabel lengthLabel;
    private javax.swing.JTextField lengthTextField;
    private javax.swing.JLabel maxCargoCapacityLabel;
    private javax.swing.JTextField maxCargoCapacityTextField;
    private javax.swing.JComboBox<String> modelComboBox;
    private javax.swing.JLabel modelLabel;
    private javax.swing.JLabel mpgLabel;
    private javax.swing.JComboBox<String> navigationSystemComboBox;
    private javax.swing.JLabel navigationSystemLabel;
    private javax.swing.JLabel priceLabel;
    private javax.swing.JTextField priceTextField;
    private javax.swing.JLabel productionYearLabel;
    private javax.swing.JTextField productionYearTextField;
    private javax.swing.JButton saveAdvanceBtn;
    private javax.swing.JLabel seatQuantityLabel;
    private javax.swing.JTextField seatQuantityTextField;
    private javax.swing.JComboBox<String> seatTypeComboBox;
    private javax.swing.JLabel seatTypeLabel;
    private javax.swing.JLabel serialNumberLabel;
    private javax.swing.JTextField serialNumberTextField;
    private javax.swing.JComboBox<String> transmissionComboBox;
    private javax.swing.JLabel transmissionLabel;
    private javax.swing.JButton uploadBtn;
    private javax.swing.JLabel widthLabel;
    private javax.swing.JTextField widthTextField;
    // End of variables declaration//GEN-END:variables
}
